/**
 * Represents a single audio track within a music set.
 * Each track is a separate audio file (e.g., deactivator.mp3, elasticity.mp3).
 */
export interface MusicTrack {
  /** Unique identifier for the track (e.g., "deactivator") */
  id: string;
  /** Display name for the track (e.g., "Deactivator") */
  name: string;
  /** Path to the audio file relative to public directory (e.g., "/audio/zone1/deactivator.mp3") */
  path: string;
}

/**
 * Represents a music set containing multiple tracks that play together.
 * Each music set is a complete song/composition made up of individual tracks.
 */
export interface MusicSets {
  /** Numeric identifier for the music set */
  id: number;
  /** Internal name matching the directory */
  name: string;
  /** User-facing display name */
  displayName: string;
  /** Array of tracks belonging to this music set */
  tracks: MusicTrack[];
}

/**
 * Represents the runtime state of a single track during playback.
 * This is separate from MusicTrack because it contains mutable playback state.
 */
export interface MusicTrackState {
  /** Track identifier matching MusicTrack.id */
  id: string;
  /** Track name for display */
  name: string;
  /** Whether the track is manually muted by the user (persistent across solo operations) */
  isMuted: boolean;
  /** Whether the track is soloed (when true, non-soloed tracks are temporarily muted) */
  isSolo: boolean;
  /** Computed: true if muted OR solo-muted (isMuted || (anySoloActive &&
   * !isSolo)) - left as value instead of function for react*/
  isEffectivelyMuted: boolean;
  /** Volume level from 0 (silent) to 1 (full volume) */
  volume: number; // 0-1
  /** Stereo pan position from -1 (full left) to 1 (full right), 0 is center */
  pan: number; // -1 to 1
}

/**
 * Contains the Web Audio API nodes for a single track.
 * These nodes form a chain: source → gain → pan → analyzer → music set output
 */
export interface MusicTrackNodes {
  /** AudioBufferSourceNode - plays the audio buffer (one-time use, recreated on each play) */
  source: AudioBufferSourceNode;
  /** GainNode - controls volume and mute */
  gain: GainNode;
  /** StereoPannerNode - controls left/right positioning */
  pan: StereoPannerNode;
  /** AnalyserNode - provides per-track frequency analysis */
  analyzer: AnalyserNode;
}

/**
 * Contains all loaded data for a music set including buffers and Web Audio nodes.
 * Only one music set is loaded at a time to conserve memory.
 */
export interface MusicSetData {
  /** The music set ID this data belongs to */
  setId: number;
  /** Decoded audio buffers for all tracks in the music set */
  buffers: AudioBuffer[];
  /** Web Audio node chains for all tracks in the music set */
  nodes: MusicTrackNodes[];
  /** The master gain node for this music set (parent node for all tracks) */
  musicSetNode: GainNode;
  /** Map of track IDs to their analyzer nodes for per-track audio analysis */
  trackAnalyzers: Map<string, AnalyserNode>;
}

/**
 * Global audio system state managed by AudioContext.
 * This represents the entire state of the audio system at any given time.
 */
export interface AudioState {
  /** Whether the audio system has been initialized (user interaction required) */
  isInitialized: boolean;
  /** Whether the master output is muted */
  isMasterMuted: boolean;
  /** Master volume level (0-1) applied to all audio output */
  masterVolume: number;
  /** ID of the currently loaded and playing music set, null if none */
  currentSet: number | null;
  /** ID of the music set currently being loaded, null if none (used for loading UI) */
  loadingSet: number | null;
  /** Map of music set IDs to their loaded data (typically only contains current music set) */
  loadedSets: Map<number, MusicSetData>;
  /** Array of track states for the current music set */
  tracks: MusicTrackState[];
  /** Whether audio is currently playing */
  isPlaying: boolean;
}

/**
 * Configuration for the audio system including available music sets and default settings.
 * This is generated by scanning the public/audio/ directory structure.
 */
export interface AudioConfig {
  /** Array of all available music sets discovered from the file system */
  musicSets: MusicSets[];
  /** Default settings applied when loading new music sets or tracks */
  defaultSettings: AudioConfigDefaultSettings;
}

/**
 * Configuration of default settings for handling audio in the app.
 */
export interface AudioConfigDefaultSettings {
  /** Default master volume level (0-1) */
  masterVolume: number;
  /** Default volume for individual tracks (0-1) */
  trackVolume: number;
  /** Default pan position for tracks (0 = center) */
  trackPan: number;
}
